general:
  buildTool: "mta"
service:
  stages:
    Build:
      stringVariables:
        - name: "CUSTOM_PARAM"
          value: "World"
      runLast:
        command: "pwd && ls -lA && ./script.sh $CUSTOM_PARAM"
stages:
  Build:
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
  Malware Scan:
    malwareExecuteScan: false
  Acceptance:
    cloudFoundryDeploy: false
    npmExecuteEndToEndTests: false
  Compliance:
    sonarExecuteScan: false

steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"